### ISSUE TITLE
jspm support

### ISSUE THREAD

**Issue by MarkehMe** [components/zepto#8]
Is it possible we could add support for jspm?

**Comment by RobLoach** [comment]
How do we we add the optional modules?

**Comment by MarkehMe** [comment]
Oops this is embarrassing, I was doing something wrong on my end. 

My apologies.

**Comment by RobLoach** [comment]
@MarkehMe There's a related issue on this one: https://github.com/components/zepto/issues/1

You might like to post your experience there. :+1:
